=== Rodez-IUT/dut-info2-filmprovider-YannMallol/Part1-XML-DTD/resources/XML2/Librairie.dtd
<!ELEMENT librairie (en-tête, livre+)>
<!ELEMENT en-tête (#PCDATA|strong|em|img)*>
<!ELEMENT livre (titre,auteurs+,description,prix)>
<!ATTLIST livre ISBN ID #REQUIRED>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED
              title CDATA #IMPLIED
>
<!ELEMENT auteurs (auteur+|collectif)>
<!ELEMENT collectif (direction,membres)>
<!ELEMENT membres (#PCDATA)>
<!ELEMENT direction (nom,prenom?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT auteur (nom,prenom)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT description (#PCDATA|strong|em|img)*>
<!ELEMENT prix (#PCDATA)>

<!ATTLIST prix devise (euro|livre|dollard) "euro"
               type  (HT|TTC) "HT"
               tva CDATA #FIXED "5.5"
>


<!ELEMENT  parametre ((nom,prenom)|direction)(#PCDATA|strong|em|img)*>
<!ENTITY  entite "©Librairie & Internet 2020">

=== Rodez-IUT/dut-info2-filmprovider-YannMallol/Part1-XML-DTD/resources/XML2/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">

<librairie>

    <en-tête>Nous sommes ici dans l'en-tête et nous pouvons utiliser plusieurs balises :
    <strong> ici la balise strong </strong>
        <em> Ici em </em>
        <img src="souce.jpg" title="Immage"/>
             ou du texte au millieu
        <em> et une autre balise </em>
    </en-tête>
    
    <livre ISBN="12">
        <titre> Premier livre</titre>
        <auteurs>
            <auteur>
                <nom> De La Fontaine</nom>
                <prenom> Jean</prenom>
            </auteur>

            <collectif>
                <direction>
                    <nom> Mallol</nom>
                </direction>
                <membres> Ici on peut voir les membres</membres>
            </collectif>
        </auteurs>
        <description> Ici une description semblable à l'en-tête
            <strong> ici la balise strong </strong>
            <em> Ici em </em>
            <img src="souce.jpg" title="Immage"/>
            ou du texte au millieu
            <em> et une autre balise </em>
        </description>
        <prix  devise="dollard" type="HT" tva="5.5"> 12 </prix>
    </livre>
</librairie>
